### ISSUE TITLE
Try all `./t/*.rakutest` files

### ISSUE THREAD

**Issue by pheix** [pheix/raku-trove#1]
From https://www.reddit.com/r/rakulang/comments/zlnugw/day_14_trove_yet_another_tap_harness_pheix_team/ by @melezhik

> Hi! Trove looks really interesting. The one "issue" I have with it is a user has to insert `raku t/test.rakutest` for every test under `t/` directory, that's tedious on my view. Would Trove allow something like `raku t/*.rakutest` as a test step within config file?
>
> Other than that this is a great tool and I am looking forward to play with Trove and SparrowCI integration...

**Comment by pheix** [comment]
I added the feature to explore some folder and build stages from matched members.

The config is:

```
target: Trove dynamic tests
explore:
  base: ./t
  pattern: (<[013]>+).(t|rakutest)
  interpreter: raku
  recursive: 1
```

It's passed both on [github](https://github.com/pheix/raku-trove/actions/runs/3800716944/jobs/6464450612#step:9:1) and [gitlab](https://gitlab.com/pheix/raku-trove/-/jobs/3534323414#L70).

By default `interpreter` is set to `raku` and `recursive` is switched off, so these members could be ommited, `pattern` is just a Raku regexpr.
